### ISSUE TITLE
Modulus not working in floating DT

### ISSUE THREAD

**Issue by Mondalgithub** [photon-lang/photon-compiler#13]
- [ ] Beta 0.1?
- [ ] Beta 0.1.6?
- [x] Beta 0.1.7?

Bug Trace Output:
Value : 45
PDB-8
1) Print Value
2) Set Value (Important: Set Value First before using anything else)
3) Increment Once
4) Decrement Once
5) Add By
6) Subtract By
7) Multiply By
8) Modulus By
9) Print DSize
0) Back to main menu
 >> 8
Value : 9
ml.photon.compiler.internals.exceptions.UnsupportedOperationException: Modulus Binary operand is invalid for Floating point variables
	at ml.photon.compiler.internals.variables.FloatingPointDataType.modulusBy(FloatingPointDataType.java:195)
	at ml.photon.compiler.main.Main.pdbelse(Main.java:143)
	at ml.photon.compiler.main.Main.main(Main.java:42)
	at ml.photon.compiler.main.Main.pdbelse(Main.java:147)
	at ml.photon.compiler.main.Main.main(Main.java:42)

PDB:
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [x] 8
- [ ] 9
- [ ] 10
- [ ] 11

Please add Beta 0.2 Milestone to this issue.

**Comment by ChlorinePentoxide** [comment]
Floating point do not support modulus. That is obvious. When you divide two floats you end up having no remainder so modulus is no use
